### ISSUE TITLE
'Template not found' on basic usage

### ISSUE THREAD

**Issue by danielbom** [scanapi/scanapi#196]
When I run

```bash
scanapi contracts.yaml
```

I got the follow error message

```bash
Loading file contracts.yaml
Writing documentation
Traceback (most recent call last):
  File "/home/daniel/.local/bin/scanapi", line 10, in <module>
    sys.exit(main())
  File "/home/daniel/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/daniel/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/daniel/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daniel/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/daniel/.local/lib/python3.7/site-packages/scanapi/main.py", line 55, in main
    scan()
  File "/home/daniel/.local/lib/python3.7/site-packages/scanapi/scan.py", line 60, in scan
    write_report(results)
  File "/home/daniel/.local/lib/python3.7/site-packages/scanapi/scan.py", line 70, in write_report
    reporter.write(results)
  File "/home/daniel/.local/lib/python3.7/site-packages/scanapi/reporter.py", line 24, in write
    content = render(template_path, context, has_external_template)
  File "/home/daniel/.local/lib/python3.7/site-packages/scanapi/template_render.py", line 10, in render
    chosen_template = env.get_template(template_path)
  File "/home/daniel/.local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/daniel/.local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/daniel/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/daniel/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: html.jinja
```

Content in contracts.yaml file, seems correct

```
api:
  endpoints:
    - name: contracts
      path: 'localhost:3602/api/'
      requests:
        - name: list amounts
          path: amounts/
          method: get
          tests:
            - name: status code is 200
              assert: ${{ response.status_code == 200 }}
```

**Comment by camilamaia** [comment]
Let me check it @danielbom! 👀

**Comment by camilamaia** [comment]
@danielbom the github action to upload to PyPI seems not working as expected. 

I did the release manually and it seems that is working now. Would you mind to reinstall and test it again, please? Sorry for the inconvenient.

**Comment by joseterra** [comment]
@camilamaia 

I test it at the moment and now it is working correctly.

Thanks!

**Comment by camilamaia** [comment]
@joseterra  thank you very much! 🚀

**Comment by camilamaia** [comment]
I've created a new issue to investigate better the github action issue: https://github.com/scanapi/scanapi/issues/201

**Comment by danielbom** [comment]
I did, and works! Thanks.

**Comment by camilamaia** [comment]
thank you @danielbom !
