### ISSUE TITLE
TemplateNotFound error when releasing with Gihub Action `publish-to-pypi.yml`

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#201]
When we publish ScanAPI to PyPI using the [GitHub Action](https://github.com/scanapi/scanapi/blob/master/.github/workflows/publish-to-pypi.yml), we are facing the following error (no matter the spec):

```shell
$ scanapi api.yaml
Loading file ../scanapi-examples/pokeapi/.scanapi.yaml
Loading file ../scanapi-examples/pokeapi/api.yaml
Writing documentation
Traceback (most recent call last):
  File "/Users/camilamaia/envs/scanner-test/bin/scanapi", line 8, in <module>
    sys.exit(main())
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/scanapi/main.py", line 55, in main
    scan()
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/scanapi/scan.py", line 60, in scan
    write_report(results)
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/scanapi/scan.py", line 70, in write_report
    reporter.write(results)
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/scanapi/reporter.py", line 24, in write
    content = render(template_path, context, has_external_template)
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/scanapi/template_render.py", line 10, in render
    chosen_template = env.get_template(template_path)
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/camilamaia/envs/scanner-test/lib/python3.7/site-packages/jinja2/loaders.py", line 249, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: html.jinja
```

Examples:

Release 1.0.0: https://pypi.org/project/scanapi/1.0.0/#files
Release 1.0.1: https://pypi.org/project/scanapi/1.0.1/#files
Release 1.0.2 https://pypi.org/project/scanapi/1.0.2/#files

Note, that for these 3 examples above, the file `html.jinja` is indeed not there. However, I added the file `MANIFEST.in` for the release 1.0.3 and it publishes the template file too, but the error persists:

Release 1.0.3: https://pypi.org/project/scanapi/1.0.3/#files

```bash
▶ ls ~/Desktop/scanapi-1.0.3/scanapi/templates
html.jinja
```

I could only fix it manually releasing the lib:

```bash
$ sudo rm -r dist/*
$ python3 setup.py sdist bdist_wheel
$ twine upload dist/*
```

More info at: https://github.com/scanapi/scanapi/issues/196

**Comment by camilamaia** [comment]
Closed by #207
